### ISSUE TITLE
Enchantment Glint

### ISSUE THREAD

**Issue by Altpapier** [Altpapier/GlintCreator#1]
The enchantment glint this is using is from https://minecraft.fandom.com/wiki/User:MrJam003/Animated_Sprites_Render. That glint only includes a version with a black background. I removed the black background from all the provided images, but the glint does not look 100% like the original in Minecraft. If you have a transparent version of the enchantment glint, please make a PR! The original enchantment glint can be found in `glint/ORIGINAL`

**Comment by FlorianWendelborn** [comment]
I think it’s possible to recreate it by using the same method Minecraft itself uses. Here’s some info on it:
- https://www.reddit.com/r/Minecraft/comments/b36po3/comment/eiyn9yv/?context=3
- https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/resource-pack-discussion/1256314-the-all-inclusive-guide-to-texturing#misc

**Comment by Altpapier** [comment]
> I think it’s possible to recreate it by using the same method Minecraft itself uses. Here’s some info on it:
> - https://www.reddit.com/r/Minecraft/comments/b36po3/comment/eiyn9yv/?context=3
> - https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/resource-pack-discussion/1256314-the-all-inclusive-guide-to-texturing#misc

Hello! My current problem is that I don't have any information about the numbers used for the enchantment glint. Like what exact color is the enchantment glint (not just its purple) or how transparent it is. I also don't know with what (free) program it would be possible to do something like this

**Comment by FlorianWendelborn** [comment]
> Color

There’s of course no guarantee that this is what they did, but often developers would just end-up picking one of the colors they’re already using. So, I’d suggest trying out if `Dark Purple` or `Light Purple` from this list match: https://www.digminecraft.com/lists/color_list_pc.php

It’s certainly not trivial, but I think you can try to extract all the necessary values from the game itself.

Maybe this will lead to good results:

1. Make a custom texture pack where you have the following 4 items:
    1. An item with an entirely black texture
    2. An item with an entirely white texture
    3. An item with a texture colored in `Dark Purple`
    4. An item with a texture colored in `Light Purple`
2. If the enchantment effect doesn’t show up on 1.3 or 1.4 then you got your color already confirmed which is great
3. For the transparency, you should be able to get a good estimate by taking a screenshot and trying to overlay the glint from the game files over it until you have a match. Then, compare the pixel values from the screenshot and see how light they are compared to the `glint.png`
4. For the speed, you can use a video recording over 60s or so and then count the repetitions. That should give you some pretty good accuracy

Also, I don’t think you’d need to be 100% correct in calculating the values. Most developers will simply pick any number that’s convenient and looks good enough (e.g. 0.4 opacity rather than 0.395 opacity).

> What free program would be possible

I looked at the source-code of the library and it seems like you’re already using a canvas-like API. As far as I know, you should be able to just calculate the animation from the original `glint.png`, the speed, the opacity, and the color. So, no program would be necessary for this. This would also allow you to make custom frame rates possible as it’s just the same thing with more steps in the movement

---

To be honest, I somewhat doubt that they’re even using transparency. Most likely, the glint.png just gets colored with one of the 2 purple shades from above and then blended with the item itself via one of these blend modes: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

The texture itself is already grayscale which points to it having no need for transparency

**Comment by Altpapier** [comment]
> To be honest, I somewhat doubt that they’re even using transparency. Most likely, the glint.png just gets colored with one of > the 2 purple shades from above and then blended with the item itself via one of these blend modes: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode
> 
> The texture itself is already grayscale which points to it having no need for transparency

Thanks for telling me that! I didn't even think of the blend modes, and I think that could solve the issue already tested it out a bit
